security:
    encoders:
        App\Entity\Doctor:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMINISTRATOR: [ROLE_SITE_USER, ROLE_SITE_DOCTOR]

    providers:
        site:
            entity:
                class: App\Entity\Doctor
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        site:
            anonymous: ~
            user_checker: App\Security\UserChecker
            pattern:      ^/
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: login
            provider: site
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
