magephp:
    log_dir: /tmp
    environments:
        medapp:
            user: app
            branch: master
            from: ./
            host_path: /www
            releases: 3
            exclude:
                - var/cache
                - var/log
                - assets
                - tests
                - infra
            hosts:
                - 0.0.0.0
            pre-deploy:
                - git/update
                - composer/install
            on-deploy:
                - symfony/cache-warmup: { env: 'prod' }
                - fs/copy: { from: 'config/env/%environment%.env', to: '.env' }
                - exec:  { cmd: 'gulp build', desc: 'Building assets ...' }
            post-release: