magephp:
    log_dir: /tmp
    environments:
        medapp:
            user: root
            branch: master
            from: ./
            host_path: /home/app/medapp
            releases: 3
            exclude:
                - var/cache
                - var/log
                - vendor
                - assets
                - tests
                - infra
            hosts:
                - medapp
            pre-deploy:
                - git/update
                - composer/install
            on-deploy:
                - symfony/cache-warmup: { env: 'prod' }
                - fs/copy: { from: 'config/env/%environment%.env', to: '.env' }
            post-release:
